### ISSUE TITLE
Doesn't launch specific config for Hekate

### ISSUE THREAD

**Issue by shadow2560** [Hartie95/fastCFWswitch#1]
Hi,

I've tried to launch a config of Hekate with this overlay, Hekate launch but the config not.

My config section for the overlay is:
```
[OFW_via_hekate]
name=OFW_via_hekate
path=/payloads/hekate.bin
bootId=Stock
```

I also have the config [Stock] defined in my "/bootloader/hekate_ipl.ini" and I use the version 5.2.0 of Hekate. I've tested it with Atmosphere via Fusee-primary, Atmosphere via Hekate and SX OS, same result.

Am I missing something?

I join you a zip with my config files for Hekate and for the overlay, maybe it will be better for you to find what's going wrong (I have some config sections with a "bootId" with a string of more than 7 chars but even without them the "Stock" config doesn't want to launch).
[configs.zip](https://github.com/Hartie95/fastCFWswitch/files/4713274/configs.zip)

Note: The param bootPos work well according to my tests.

**Comment by romracer** [comment]
I found no instance of `id=` in your hekate_ipl.ini.  You need to define an id (which is a maximum of 7 characters).  The id is not the name in `[ ]`.

See the hekate [README](https://github.com/CTCaer/hekate/blob/master/README.md) for more details (search for `id=idname`)

**Comment by shadow2560** [comment]
Thanks, I haven't seen this param in the Hekate's config, this explain all!

I will test this and close this issue if it work, thanks again.

**Comment by Aliasim800** [comment]
I still don't understand how this works. Can somebody explain please?
