### ISSUE TITLE
Menu not loading

### ISSUE THREAD

**Issue by KamiSquadX** [Hartie95/fastCFWswitch#18]
How do you do this? I tried pressing L + Dpad Down + Click Right Joystick, nothing is happening.

At least have a readme with instructions on how to use this.

**Comment by Hartie95** [comment]
Do you have the tesla menu setup?
This is running on top of the tesla overlay system module and started by the tesla overlay menu.
The Readme should already contain them as requirements, and have informations about things specific about this overlay.
