### ISSUE TITLE
My OCD made me report this. :)

### ISSUE THREAD

**Issue by LampDork** [Hartie95/fastCFWswitch#4]
![example](https://user-images.githubusercontent.com/81010917/111864428-759e4000-8926-11eb-9a3d-a0a9f41bc802.PNG)

Main 'example' / template has a double up. Hekate x2 in the overlay could be confusing for some.

**Comment by Hartie95** [comment]
Oh, missed that, thx. I will fix it with the next release in the near future, where i add support for hekates rebbot to ums feature ^^
