### ISSUE TITLE
Fastcfwswitch on SXCORE unit tested

### ISSUE THREAD

**Issue by hongtm77** [Hartie95/fastCFWswitch#6]
Hi, I have a patched switch running dual boot Emunand and L4t Ubuntu. And I have successfully installed fastcfwswitch with Tesla overlay. But whenever I'm trying to Boot to Ubuntu from Fascfwswitch, I got into hekate instead. I'm not sure where is the Ubuntu .bin file is located. Please help

**Comment by Hartie95** [comment]
For ubuntu and Android you need to point fastCFWswitch to the hekate bin, and set the bootId defined in the .ini file from ubuntu/android.
If you didn't change anything its probably `SWR-UBU` for ubuntu and `SWANDR` for android.

**Comment by hongtm77** [comment]
Hi thanks for the response. It works! Really appreciate it 👍👍🔥
